### ISSUE TITLE
It have a long tone when play midi file 

### ISSUE THREAD

**Issue by freeheart** [Tonejs/MidiConvert#102]
I play midi file at "https://tonejs.github.io/Midi/",It have a long tone when play midi file

**Comment by tambien** [comment]
@freeheart what are the steps to reproduce this error?

**Comment by yeemachine** [comment]
@tambien 
Would like to also second this issue. Haven't looked into it too much, perhaps it might have to do with clearing out the old synths in that example on your site? https://tonejs.github.io/Midi/
`synth.dispose()`
I'll get that long tone playing when switching between files and pressing the play button too quickly. Or if there are too many tracks in the next midi file... kinda inconsistent finding atm.
