### ISSUE TITLE
Running server-side: ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by livemixlove** [Tonejs/MidiConvert#12]
Is Midiconvert client-side only?   Any work arounds to this?  Thank you!

**Comment by livemixlove** [comment]
Problem line: https://github.com/Tonejs/MidiConvert/blob/445102d7cf5c0fbc355ee906b7b43ffadf9d0178/src/Midi.js#L32

**Comment by livemixlove** [comment]
Might fork and make a server-side check here and use fs instead of XMLHttpRequest.

**Comment by tambien** [comment]
There's an example in the [README](https://github.com/Tonejs/MidiConvert#raw-midi-parsing) of using MidiConvert with Node.js. Just use the `parse` method instead of the `load` method.

**Comment by livemixlove** [comment]
Great, thank you!  Sorry I missed that example!
