### ISSUE TITLE
endOfTrack event should be duration

### ISSUE THREAD

**Issue by JackCA** [Tonejs/MidiConvert#122]
Currently, the duration of a track (and a file) are determined by the the last note event's start + duration.

However, there can/should be an `endOfTrack` event on each track that can take place after the above location.

It looks like there's some [checked-in commented-out code](https://github.com/Tonejs/Midi/blob/master/src/Track.ts#L103) that was heading down this track.

Any thoughts on this? I could try and finish it out.

**Comment by tambien** [comment]
Closed by #123
