### ISSUE TITLE
when I use the "Basic Example" i get an error: "fetch is not defined"

### ISSUE THREAD

**Issue by danielnachumdev** [Tonejs/MidiConvert#132]
const express = require("express");

const { Midi } = require('@tonejs/midi');

const app = express();

app.get("/",(req,res)=>{
    a();
    res.send("Hello");
})

async function a(){
    try{
        const midi = await Midi.fromUrl("./test2.mid");
        console.log(midi);
        //the file name decoded from the first track
        const name = midi.name;
        //get the tracks
        midi.tracks.forEach(track => {
            //tracks have notes and controlChanges

            //notes are an array
            const notes = track.notes
            notes.forEach(note => {
                //note.midi, note.time, note.duration, note.name
                console.log(note.name);
            })

            //the control changes are an object
            //the keys are the CC number
            track.controlChanges[64]
            //they are also aliased to the CC number's common name (if it has one)
            track.controlChanges.sustain.forEach(cc => {
                // cc.ticks, cc.value, cc.time
            })

            //the track also has a channel and instrument
            //track.instrument.name
        })
    }
    catch(err){
        console.error("USER ERROR: " + err);
    }
}

app.listen(3000,function(){
    console.log("Server Started on port 3000!");
})

**Comment by ByDSA** [comment]
'Midi' class accepts an ArrayBuffer as argument. You can do this:

```
const fs = require("fs");

const file = fs.readFileSync("./test2.mid");
const midi = new Midi(file);
```

**Comment by tambien** [comment]
@ByDSA thanks for jumping in!
