### ISSUE TITLE
Converto Json to Midi

### ISSUE THREAD

**Issue by sergisabater** [Tonejs/MidiConvert#165]
Hi!

It is possible to reconvert a Json output from your converter (https://tonejs.github.io/Midi/) to a Midi file? I am using that output to build my own files in Unity, and being able to reconvert it again to Midi would be incredible.

Thanks!

**Comment by alindsay55661** [comment]
@sergisabater  Does this work for you?

https://github.com/Tonejs/Midi#encoding-midi

**Comment by sergisabater** [comment]
That should work for me, many thanks!
