### ISSUE TITLE
Convert Midi into JSON

### ISSUE THREAD

**Issue by BaptisteHardelin** [Tonejs/MidiConvert#189]
Hi all I'm trying to make an app with vuejs, for the moment I just want to convert the midi file to json but on any midi file I've tried I get this error Expected 'MHdr', got: '<!DO' here's the code (I create my midi files with guitare pro 8)

Vue js page

```
<template>
  <div>
    Learn Page
    <textarea v-model="midiContent" placeholder="json output..."></textarea>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import { Midi } from "@tonejs/midi";

const midiFilePath = "@/assets/test.mid";
const midiContent = ref("");

onMounted(async () => {
  try {
    const response = await fetch(midiFilePath);
    const midiArrayBuffer = await response.arrayBuffer();

    const midi = new Midi(new Uint8Array(midiArrayBuffer));
    console.log(midi);
  } catch (error) {
    console.error(error);
  }
});
</script>

<style scoped>

</style>
```

![image](https://github.com/Tonejs/Midi/assets/91209529/b9b6a712-af70-4d3f-877c-fbf6bbcb649c)
![image](https://github.com/Tonejs/Midi/assets/91209529/68c1f7ae-0161-4145-b629-fb15d7b05b27)
[test.zip](https://github.com/Tonejs/Midi/files/13762834/test.zip)

**Comment by Ninhache** [comment]
I'm not sure, but it might be related to a CORS error since <!DO resembles <!DOCTYPE... or it could be something else

Look around at the request you're making in the devtools, maybe you will find an answer there

**Comment by BaptisteHardelin** [comment]
it was the CORS, thank you very much!
