### ISSUE TITLE
global namespace with requirejs

### ISSUE THREAD

**Issue by ghost** [Tonejs/MidiConvert#29]
I am having issues with the anonymous functionality registered as **AMD** in requirejs:

`Uncaught ReferenceError: MidiConvert is not defined`

**Comment by tambien** [comment]
MidiConvert has a UMD header on it, so it should work with AMD and CMD. If you are using requirejs, MidiConvert won't be on the global namespace, you'll have to 'require' it.

How are you currently using or importing MidiConvert into your project?

**Comment by ghost** [comment]
**Uncaught ReferenceError: MidiConvert is not defined**
```
requirejs.config({
    //By default load any module IDs from js/lib
    baseUrl: 'js/lib',
    //except, if the module ID starts with "app",
    //load it from the js/app directory. paths
    //config is relative to the baseUrl, and
    //never includes a ".js" extension since
    //the paths config could be for a directory.
    paths: {
        app: '../app',
	jquery: 'jquery-3.1.1.min',
	knob: 'jquery.knob.min',
	tone: 'Tone',
	MidiConvert: 'MidiConvert'
    }
});


// Start the main app logic.
requirejs(['jquery', 'knob', 'tone', 'MidiConvert', 'app/control'],
function   ($, MidiConvert) {});
```

**Comment by ghost** [comment]
`Uncaught TypeError: Cannot read property 'parse' of undefined
`

**Comment by ghost** [comment]
https://github.com/subunits/Instrument/tree/master

**Comment by tambien** [comment]
Just tested out MidiConvert with requirejs myself and the UMD header worked fine for me. 

I think your issue is that your function parameter names don't line up with your include array

```javascript
requirejs(['jquery', 'knob', 'tone', 'MidiConvert', 'app/control'],
function   ($, knob, Tone, MidiConvert, control) {});
```

**Comment by ghost** [comment]
Thank you for your time 👍
