### ISSUE TITLE
De-sync? w/example

### ISSUE THREAD

**Issue by sliceofcake** [Tonejs/MidiConvert#32]
I have run MidiConvert on a certain MIDI file, and the time information reported, after a few seconds, is de-synced from the actual notes times.
The MIDI is from Super Mario World, found here [http://www.ninsheetmusic.org/download/mid/844].
The last chord in the midi sounds at approximately [4m:01s] ("correct").
The last chord in the MidiConvert reports as approximately 277s=[4m:37s] ("de-synced").

I can only guess that tempo changes aren't accounted for in the note times reported by MidiConvert, resulting in de-sync, but I would like to hear what you think could be causing this, as the developer.

**Comment by tambien** [comment]
You're correct in your assumption. MidiConvert does not currently handle tempo changes. It will just take whatever the last tempo of the song is and use that throughout.

**Comment by YuiyuD** [comment]
Thanks @sliceofcake  for notice this!
