### ISSUE TITLE
timeSiganture in the header and all controlChanges in the Tracks are gone after encoding

### ISSUE THREAD

**Issue by Blackfaded** [Tonejs/MidiConvert#43]
Hey, great module!
But I have an issue - wehen I read a midi File and directly encode it to a new file, the timeSiganture in the header and all controlChanges in the Tracks are gone. Also the timemal is gone. the sourcefile when imported into my DAW has a timemap and creates the BPM around it, with the encoded file there is no time map.

Can someone help?

**Comment by tambien** [comment]
moved to new midi parser. this should be fixed now.
