### ISSUE TITLE
Note number to note name convert

### ISSUE THREAD

**Issue by dcromster** [Tonejs/MidiConvert#46]
Hello!

it would be nice to set the parameter to get not the note number, but its name.

~~Tell me, please, where can I see the ratio of the note number and its name? Like 63 = note 'C' 2nd octave~~
I fount this (in russian): https://webhamster.ru/mytetrashare/index/mtb0/1343982148vkmqs7k7ig

**Comment by appsforartists** [comment]
Looks like `midiToPitch` is what you're asking for: https://github.com/Tonejs/MidiConvert/blob/master/src/Util.js
