### ISSUE TITLE
Cannot minify build with Create React APP

### ISSUE THREAD

**Issue by DrSkunk** [Tonejs/MidiConvert#49]
When a blank Create React App is created and MidiConvert is a dependency, it is fine for developing. As soon as a build is started it gives the following error:
```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/midiconvert/src/Util.js:20

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

In the package.json from MidiConvert the following entry triggers the build of the source files.
`  "module": "src/MidiConvert.js",`
When removed, the React project builds.

[React project implementing MidiConvert.](https://github.com/Wintergatan/midipunch-react)
[Package JSON with erroring line of MidiConvert.](https://github.com/Tonejs/MidiConvert/blob/master/package.json#L6)

**Comment by appsforartists** [comment]
> still precompile other ES6 features to ES5 if it intends to support older browsers

@gaearon curious about your thoughts here.  ES2015 has been well supported across browsers for years, so I'm not terribly inclined to translate our builds to ES5.  The operative word in your docs is _if_, but I'm not sure if there's an alternative when a package doesn't support ES5 (other than to fork, as you mention later in those docs).

**Comment by appsforartists** [comment]
I just looked at the `module` line, and it's pointing directly to our `src` folder, which makes me even less inclined to touch it.

**Comment by DrSkunk** [comment]
Hello @appsforartists

Would you like me to open the issue over at the React repository?

**Comment by appsforartists** [comment]
If you want to, sure.  It would be the create-react-app repo, and I don't know what they'd do.  As I understand it, CRA is supposed to be a zero-config starter, which means there isn't a place to add exceptions.

But, requiring all dependencies to be ES5 seems heavyhanded, especially if you're importing from ES2015 modules.  At the very least, I think they ought to fall back to `main` if `module` isn't ES5.  (I'm still not convinced it makes any sense for them to require ES5 dependencies, but I don't know enough about that project to make a definitive statement.)
