### ISSUE TITLE
bpm and duration not accurate

### ISSUE THREAD

**Issue by raphaellaxz** [Tonejs/MidiConvert#52]
When I using the parse method, the result JSON header's bpm is a long decimal number,e.g. the bpm is 94, and the result from the JSON is 94.80005877603644.
I am working on  changing durations of notes into beats, and it hinder my calculations.
besides, the durations of notes is hard to check as well as the decimal is so long, but I do not really sure if it is due to the bpm accuracy of anyother problems.

**Comment by tambien** [comment]
these values are just calculated from the MIDI file and shown with the most accuracy. try `value.toFixed(precision)` if you'd like it in a more human readable form.
