### ISSUE TITLE
midi is not saving correctly on web browser.

### ISSUE THREAD

**Issue by fornof** [Tonejs/MidiConvert#53]
so I decided to make a heroku app here so you can see my predicament: 
https://demo-for-midi-convert.herokuapp.com/
github for this experiment is at: 
https://github.com/fornof/Midi-Keytone 
1. I can get a download of a midi.encode() , but none of my midi players can play it ( see button 1 download). 
2. I can hear a midi/tone.js in the browser, i just cannot export at the moment (play a key or something)
3. The demo uses fs to write the midi file, but my demo uses a file blob and midi.encode. I don't think midi.encode is working the way it should work. it is a string not a binary object. 

This is what a midi file read in looks like. 
MThd�MTrk�X`�A�Q�/MTrk���G�Cd�|�Cd�Cd\�Cd�Ed\�Ed�Gd\�Gd�Hd\�Hd�Jd�|�Jd�Jd|�Jd�Jd|�Jd�Jd|�Jd�Od�|�Od�Od\�Od�Qd\�Qd�Sd\�Sd�Td\�Td�Vd�|�Vd�>d\�>d�>d�<�>d�>d\�>d�Cd�<�Cd�/MTrk���G��2d|�2d�2d|�2d�2d|�2d�7d�|�7d�7d\�7d�9d\�9d�;d\�;d�<d\�<d�>d�|�>d�>d|�>d�>d|�>d�>d|�>d�Cd�|�Cd�Cd\�Cd�Ed\�Ed�Gd\�Gd�Hd\�Hd�Jd�|�Jd�6d\�6d�6d�<�6d�6d\�6d�;d�<�;d�/MTrkQ��U�7d�|�7d�5d�|�5d�3d�|�3d�2d�|�2d�2d\�2d�2d�<�2d�2d\�2d�2d�<�2d�/MTrk�Jeffrey M Colletti�/MTrk(� jcollett@attila.stevens-tech.edu�/MTrk�/MTrk�/MTrk�/MTrk�/MTrk�/

This is what MidiConvert midi.encode() produces from the exact same midi file read in then piped out:
MThdMTrkÿQ'ÿ/MTrk¸ÿQ'ÿUntitledÀGCd|CZCd\CZEd\EZGd\GZHd\HZJd|JZJd|JZJd|JZJd|JZOd|OZOd\OZQd\QZSd\SZTd\TZVd|VZ>d\>Z>d<>Z>d\>ZCd<CZÿ/MTrkÑÿQ'ÿUntitledÁG2d|2Z2d|2Z2d|2Z7d|7Z7d\7Z9d\9Z;d\;Z<d\<Z>d|>Z>d|>Z>d|>Z>d|>ZCd|CZCd\CZEd\EZGd\GZHd\HZJd|JZ6d\6Z6d<6Z6d\6Z;d<;Zÿ/MTrk`ÿQ'ÿUntitledÂU7d|7Z5d|5Z3d|3Z2d|2Z2d\2Z2d<2Z2d\2Z2d<2Zÿ/

I'm guessing it's not getting set to binary correctly, but I've tried "binary" "audio/midi" and "application/octet-stream" and none of them seem to produce the binary format with question marks. 
any help on this would be appreciated

**Comment by tambien** [comment]
I've heavily changed the way that midi is encoded and decoded. 

This worked for me:
```javascript
const blob = new Blob([midi.toArray()], {type : 'audio/midi'})
```
