### ISSUE TITLE
Handle Program Change Events

### ISSUE THREAD

**Issue by ArsenyYankovsky** [Tonejs/MidiConvert#56]
Hey,

I have a lot of MIDI files which are horrible. And by that I mean that all the instruments are merged into one track and the different instrument sounds are made with sending an program change event previously. Is there any plan to support that or at least parse these events?

Update:
I found that there is a code that is supposed to handle program change events, but I'm not sure how right now. I'll spend more time later and investigate that.

**Comment by tambien** [comment]
It does listen for program change event. i simply take the first program change event and set that as the tracks instrument so if you're changing instrument a lot on one track, it won't work right now.
