### ISSUE TITLE
Parcel ?? and Decoder is not a function

### ISSUE THREAD

**Issue by simdax** [Tonejs/MidiConvert#60]
Hello all.

I'm trying Parcel as packager, and I had just an error when using 
MidiConvert.parse(data)

``` Decoder is not a function  ```

I just had to add 'default' in line 80 of Midi.js
``` const midiData = Decoder.default(bytes) ```

I'm not sure where the problem could come from. I feel it could be some babel preset stuff and all that jazz ?

**Comment by rupertsworld** [comment]
I'm also having this issue.

**Comment by tambien** [comment]
major refactor. this issue should be fixed now.
