### ISSUE TITLE
Multiple tempos / BPMs

### ISSUE THREAD

**Issue by pr0jectile** [Tonejs/MidiConvert#63]
I have some songs that use multiple BPMs, but when converting using your tool, I only get one BPM as the output.

Can you look into making this tool use multiple BPMs please as an array?

Thanks.

**Comment by appsforartists** [comment]
I don't speak for @tambien, so I have no idea if this is somewhere he's interested in taking it.  I will say that PRs are more likely to be addressed than feature requests.  😃

**Comment by Topograph** [comment]
I also have problems with tracks including tempochanges...not sure how i can solve those

Edit: Nevermind. I found the [duplicate thread](https://github.com/Tonejs/MidiConvert/issues/40) of this one. And took the modified version from there....did the trick for me

**Comment by pr0jectile** [comment]
> I also have problems with tracks including tempochanges...not sure how i can solve those
> 
> Edit: Nevermind. I found the [duplicate thread](https://github.com/Tonejs/MidiConvert/issues/40) of this one. And took the modified version from there....did the trick for me

@Topograph Hey, do you mind sharing the relevant bits of code? Feels cluttered in that thread with all the commits.

**Comment by Topograph** [comment]
Hi,
It's been a while. I only found this one on my hard drive:
[MidiConvertTime.js.txt](https://github.com/Tonejs/MidiConvert/files/2761008/MidiConvertTime.js.txt)
(rename the txt file to .js, GitHub seems to only allow certain file types in here ;). )

This seems to be a minified version. Sorry I found no other. 
If I remember correctly this version considers the tempo changes when calculating the durations and starting timings in milliseconds of the notes.

**Comment by pr0jectile** [comment]
@Topograph I figured out how to build using the commits from that thread in the end and the output result does match your version so I guess they both are the same. Thanks anyway! :)

**Comment by tambien** [comment]
should be fixed in the latest release. i compare all of the tempo changed timings against output i generated from pretty_midi, so i'm pretty sure they're accurate. the tempos are stored in an array of tempo events in the header file. if this array is modified, you have to update all of the note and cc time values by calling `midi.header.update()`.
