### ISSUE TITLE
How to identify Piano tracks?

### ISSUE THREAD

**Issue by ctrl-alt-d** [Tonejs/MidiConvert#65]
How can I identify this two trakcs?

![selection_383](https://user-images.githubusercontent.com/3105983/50399169-cc376680-077d-11e9-93f6-e4380decab4d.png)

I mean:

```
piano_left_hand = __some_expression__;
piano_right_hand = __some_expression__;
```

![selection_384](https://user-images.githubusercontent.com/3105983/50401136-80d88480-078c-11e9-9082-731340ee2dd9.png)

Thanks!

**Comment by tambien** [comment]
Each track has an instrument object which will return the name of the instrument `track.instrument.name`. so that should return 'piano' in your case.
