### ISSUE TITLE
I miss one track on each song

### ISSUE THREAD

**Issue by ctrl-alt-d** [Tonejs/MidiConvert#67]
Hi,

this is the issue: I miss a track on each song. For example [The entertainer](https://github.com/ctrl-alt-d/A_F_NO7_01_viz/tree/feature/skeleton/scores) has two tracks but (it seems) only one is loaded. I have tested also with other songs, for example, in same folder, `A_F_NO7_01.mid` has one track and is not loaded.

I have tested in [my code](https://github.com/ctrl-alt-d/A_F_NO7_01_viz/blob/2a3e74c1e8188f7e166c387a604fa7f7ba3db7e0/src/sketch.js) with node `"@tonejs/midi": "^1.2.0"` library version and also I have tried deserializing on your web https://tonejs.github.io/Midi/

Best regards and thanks a lot about to share this great software!

**Comment by tambien** [comment]
In format 1 MIDI files, the first track is usually tempo and song info, all of that is put into the `header` output. Then the second track is the beginning of the note data. Could this be what is happening here?

**Comment by ctrl-alt-d** [comment]
Hi Mr @tambien,

thanks about your fast reply.

Maybe I'm doing something wrong, but I'n not able to see notes on header (1), and I only see one track (2) with notes (3).

![selection_437](https://user-images.githubusercontent.com/3105983/53305028-816cc480-387c-11e9-8df2-8a94e721186c.png)

**Comment by tambien** [comment]
I'm looking at your MIDI file a little more and it's kind of a weird file. Every Format 1 midi file i've seen reserves the first track for just meta events (tempo time signature) and then the notes start on the second track. Your midi file seems to be Format 1, but includes notes on that first track. Is this a MIDI file that you made? From everything that i've read, this is not-standard. [for example](https://www.csie.ntu.edu.tw/~r92092/ref/midi/)

**Comment by ctrl-alt-d** [comment]
Hi @tambien , I really apologize for wasting your time. This file [is download from musescore](https://musescore.com/user/14284/scores/24666) with no changes. I will look for a well-formed midi file. Congrats about your JS libraries.

**Comment by tambien** [comment]
@ctrl-alt-d no need to apologize. this is actually really helpful, it seems like my assumptions were wrong and at least some Format 1 files include notes on the first track. this is probably a pretty easy fix, so i'll look into accommodating these files and use these MIDI files in a test.

**Comment by ctrl-alt-d** [comment]
Just for your information. I've upgraded to `"@tonejs/midi": "^1.2.1"` and still only one track.

You can check it at: `https://github.com/ctrl-alt-d/A_F_NO7_01_viz/tree/feature/skeleton` with ( `npm run dev` and seeing log)

**Comment by tambien** [comment]
i checked with TheEntertainer track that you referenced, and it seems to parse two tracks. Would you try dropping that MIDI file in [here](http://tonejs.github.io/Midi/) to see if it's able to get the right number of tracks?

**Comment by ctrl-alt-d** [comment]
After upgrade to  `"@tonejs/midi": "^1.2.2"`  I get the both tracks. Good Work!
