### ISSUE TITLE
Midi.js uses 'window' and this wont work with node.

### ISSUE THREAD

**Issue by leenattress** [Tonejs/MidiConvert#68]
I swapped this variable out for 'global' in my node script and everything worked just fine.

I know you have this set up for browser usage, but this could be used in node out of the box if this was fixed. :)

**Comment by tambien** [comment]
I thought i took out all the references to the 'window' object. could you link to a line number?

**Comment by leenattress** [comment]
I did npm install @tonejs/midi

and got (among other things):

\node_modules\@tonejs\midi\build
26/10/1985  08:15            30,466 Midi.js

in there you will find:
(window, function() {


hope this helps. :)
