### ISSUE TITLE
Importing midi file broken

### ISSUE THREAD

**Issue by j0hnm4r5** [Tonejs/MidiConvert#70]
This is connected to an [issue filed](https://github.com/tensorflow/magenta-js/issues/294) with tensorflow/magenta-js.

---

# Issue
Importing a midi file (via magenta-js, which is using Tonejs Midi) fails with this error: 

```
Midi.js:86 Uncaught TypeError: Decoder is not a function
    at Midi.decode (Midi.js:86)
    at Object.parse (MidiConvert.js:43)
    at Object.midiToSequenceProto (midi_io.ts:39)
    at FileReader.<anonymous> (....js:14)
```

# Solution

`Midi.js` within the package `midiconvert` calls `Decoder(bytes)` from the `midi-file-parser` package (expecting it to be a function), except `midi-file-parser` exports that function within an object.

Changing `const midiData = Decoder(bytes)` to `const midiData = Decoder.default(bytes)` within `node_modules/midiconvert/src/Midi.js` fixes the issue.

**Comment by j0hnm4r5** [comment]
I'm actually super confused now — what is the difference between this package and the `midiconvert` package? Both have the same author and redirect here, but `midiconvert` hasn't been updated in over a year. And `Midi.js` within `@tonejs/midi`` is different from the one within `midiconvert`.

EDIT: looks like `midiconvert` was wrapped into `@tonejs/midi` with [this commit](https://github.com/Tonejs/Midi/commit/2605351b5d4c06d192e21522a4405d93ea500494#diff-f70adec9761ae64004e9d20a1a44f71e)?

**Comment by appsforartists** [comment]
This package used to be called `midiconvert`.  I'm guessing @tambien renamed/refactored it.

It sounds like your bundler is behaving differently than what one of your dependencies was tested against.

**Comment by tambien** [comment]
Closing, since i don't this is still relevant in the latest version. please reopen if there are still import issues
