### ISSUE TITLE
Midi constructor fails on iOS 9 Safari

### ISSUE THREAD

**Issue by defmech** [Tonejs/MidiConvert#71]
Hi, I'm looking into various sound frameworks for a game we are developing. Our target platforms still include the iPad 2 on iOS 9. When trying to instantiate a new Midi() by passing an ArrayBuffer it silently fails. Instantiating a new Midi() without passing an array buffer works as expected. Maybe related to this? https://stackoverflow.com/questions/14340989/blob-does-not-accept-uint8array-on-ios & https://caniuse.com/#search=Uint8Array

**Comment by tambien** [comment]
I would guess it's not related to the first SO issue since i don't recall anywhere that Blobs are used in the library. It could be an issue with the second one, but if you pass in an array of numbers instead of an ArrayBuffer, it should also work. Does it work on other browsers?

**Comment by tambien** [comment]
@defmech did you find what the specific issue was?

**Comment by tambien** [comment]
Stale issue, going to close. I've set the ts compiler to target es5, so i assume browsers that support es5 (like Safari 9) should be able to work with the API. Please reopen if you're able to find the specific issue with Safari.
