### ISSUE TITLE
New version not working

### ISSUE THREAD

**Issue by Cpavrai** [Tonejs/MidiConvert#72]
Hi, I'm using @tonejs/midi, but when I install this package with npm, I have directly this problem while I just try to import it in my file : 

> ```error TS2307: Cannot find module './midi-file'```

And this, related from the files : Header.d.ts, Instrument.d.ts, & Track.d.ts. The package being in version 2.0.0.

What may I do ? I tried with younger versions and I get problems with typescript syntax (arrays which shall have types of their elements...).

**Comment by tambien** [comment]
i think the files referenced in the package.json might be pointing to files that are no longer there.

**Comment by stephaneeybert** [comment]
I have the very same issue. 

@tambien What step do we need to take to work around that ?

**Comment by stephaneeybert** [comment]
The library source code contains missing file references.

The `@tonejs/midi/dist/Header.d.ts` file contains the source code line:

`import { MidiData } from "./midi-file";
`
But there is no such `./midi-file` file in the directory.

**Comment by stephaneeybert** [comment]
I removed the `./` suffixes in the few instances they were present in the library files, and this worked around the issue.

I still have another [issue](https://stackoverflow.com/q/56463077/958373) though.

**Comment by tambien** [comment]
ok should be fixed. sorry for the delay. just confirmed that in `@tonejs/midi@2.0.3` you can now do this:

```typescript
import { Midi } from '@tonejs/midi'
```

**Comment by stephaneeybert** [comment]
I wonder how to traverse the control changes:

This one traverses the map but returns undefined values:
```
Object.keys(midiTrack.controlChanges).map(key => {
  const midiControl: any = midiTrack.controlChanges[key];
  const control = new Control(midiControl.number, midiControl.time, midiControl.ticks, midiControl.value);
  track.controls.push(control);
});

```          
These two would not traverse the map:

```
Map.prototype.forEach((midiControl, key: number, midiTrack.controlChanges) => {
});
midiTrack.controlChanges.forEach((midiControl, key: number) => {
});

```
