### ISSUE TITLE
Demo code stale? 'sustain' is not an object, not an array

### ISSUE THREAD

**Issue by drone1** [Tonejs/MidiConvert#73]
Hello and thanks for the cool project.

I'm parsing this file: https://www.dropbox.com/s/hecoqfrjok5fsjs/KICK1.mid?dl=1

Exported from Ableton 10 via "Export to MIDI file..." or whatever.

It's simple MIDI for a kick drum, all running on a single note w/ velocity changes, but nothing else, I believe.

In your demo code, you've got something like this:
```
	  //they are also aliased to the CC number's common name (if it has one)
	  track.controlChanges.sustain.forEach(cc => {
	    // cc.ticks, cc.value, cc.time
	  })
```

But for me, track.controlChanges.sustain is an object (empty, or ``{}``), and not iterable via forEach().

I'm guessing the sample code is simply out of date, but you can inspect the MIDI file I've provided if you want, or feel free to let me know if I can provide more info.

``track.notes`` is an array and forEach() works fine. I can print note data without issue.

Full code:

```
	const fullPath = ...
	const midiData = fs.readFileSync(fullPath);
	const Midi = require('@tonejs/midi');
	const midi = new Midi(midiData);

	//get the tracks
	midi.tracks.forEach(track => {
	  //tracks have notes and controlChanges

	  //notes are an array
	  const notes = track.notes
	  notes.forEach(note => {
	    //note.midi, note.time, note.duration, note.name
	    console.log(`note: ${json(note)}`);
	  })

	  //they are also aliased to the CC number's common name (if it has one)
	  track.controlChanges.sustain.forEach(cc => { // ** ERROR **
	    // cc.ticks, cc.value, cc.time
	  })

	  //the track also has a channel and instrument
	  console.log(`instrument name: ${track.instrument.name}`)
	})
```

**Comment by drone1** [comment]
Hit me, @tambien.

**Comment by tambien** [comment]
@drone1 is this still an issue? i think the examples have been updated since you originally posted this.

**Comment by drone1** [comment]
"Basic example" from the README.md – the code has not changed:
```
  track.controlChanges.sustain.forEach(cc => {
    // cc.ticks, cc.value, cc.time
  })
```
I just tested the current repo with my same data. Now, instead of ``track.controlChanges.sustain`` being an empty object ``{}`` as I said in my original post, it's just ``undefined``, and ``track.controlChanges`` is ``undefined`` this time. 

I guess that makes sense if there is no control change data. So, expected?

Node v10.4.1. Thanks.

**Comment by KarrascoJena** [comment]
Hi, @drone1 what is the meaning of "json(note)" in your code?

**Comment by drone1** [comment]
It’s a shorthand function to convert JSON to a string.
