### ISSUE TITLE
Percussion instruments not identified

### ISSUE THREAD

**Issue by neutonfoo** [Tonejs/MidiConvert#75]
The latest version of Midi doesn't seem to identify percussion instruments (even on the linked demo http://tonejs.github.io/Midi/). I tested a few .midi files I downloaded on MuseScore and they all default to Grand Piano.

**Comment by tambien** [comment]
can you link to an example file which parses as percussion in other software, but does not work with this library? i think the test is really simple, if the channel is 10, then it is a percussion instrument, so it's possible that the channel number is not reported correctly or set somewhere else.

**Comment by LaiZhou** [comment]
+1 

@tambien 
checkout this drum midi file [http://mididrumfiles.com/files/BEAT1R.mid](http://mididrumfiles.com/files/BEAT1R.mid)
the parsed result is
```
tracks": [
    {
      "channel": 0,
      "controlChanges": {},
      "instrument": {
        "family": "piano",
        "name": "acoustic grand piano",
        "number": 0
      }

```
I use music score to print the score for this midi file, it’s a drum midi.
It's a bug.

**Comment by ritz078** [comment]
It is because of this line
https://github.com/Tonejs/Midi/blob/92796f8dc29291bba890e29241113429f6dc8f08/src/Track.ts#L54

`channel` is always passed as `0`.
