### ISSUE TITLE
Raw Midi Parsing broken - TypeError: Midi is not a constructor

### ISSUE THREAD

**Issue by DrSkunk** [Tonejs/MidiConvert#78]
Since version 2.0.5 using `Midi` as a constructor throws the error `TypeError: Midi is not a constructor`.
Example using version 2.0.5: https://repl.it/@whitebird/tonejs-midi-error-broken

Last version that was working was version 2.0.4: https://repl.it/@whitebird/tonejs-midi-error-working

It uses this snippet of code:
```javascript
const fs = require('fs');
const Midi = require('@tonejs/midi');

const midiData = fs.readFileSync('test.mid');
const midi = new Midi(midiData);
console.log(midi);
```

**Comment by DrSkunk** [comment]
Ah, so the constructor was moved, thank you.

For future reference, using `const {Midi} = require('@tonejs/midi');` instead of `const Midi = require('@tonejs/midi');` fixed it. I assume that changed after 2.0.4.

**Comment by tambien** [comment]
yes! thanks for following up here! i updated the README to reflect this info
