### ISSUE TITLE
BPM changes and their use in Tone.Transport

### ISSUE THREAD

**Issue by rnatter** [Tonejs/MidiConvert#81]
I am very grateful for your work on Tone.js and Tonejs/MIDI, and also for the recent work to include tempo changes in the parsing of midi files.

This issue is with the way parsed midi files appear to work with the Tone.Transport.
It may be that coordinating the parsed midi file BPMs with the Transport BPM is problematic.
(It is also very possible that I’m simply missing something about how it is supposed to work.)

Suppose we take a midi file composed of all quarter notes, but tempo variations every two bars, say q=120,60,90, etc. and put these notes into a Part, to schedule them along the Transport.  Tonejs/midi parses this file with the tempo changes, and the Transport plays it correctly, at least aurally.  However, the BPM of the Transport doesn’t actually change. It stays at the default of 120, or whatever it is set at. This is a problem because the Transport thinks the entire passage is at 120, and so doesn’t know where it is in the file, and does not report the position correctly. (Or, more precisely, reports the position as if the file were all at one BPM.)  

After a bit of thought, I expected this behavior.  The Transport hasn’t been told that there are BPM changes.  Maybe I just need to tell it where the BPM changes are!  There’s a method for that!  If I go through the header.tempos and Tone.Transport.schedule a new tempo value at each of the tempo changes, then the Transport might change BPM at those points and all will be well.
 
But that doesn’t work:

The midi file has already been parsed with tempo changes accounted for, so I think that setting the BPM in the Transport is making another time transformation on top of the one that was made when the midi file was parsed.  So if the parsed midi passage of quarter notes changes from 120 to 60, and I also tell the Transport at that point to change its BPM to 60, the quarter notes will actually sound TWICE as slow.  The parsed midi slows down, and I have told the Transport to slow it down again.   I’m pretty sure this is what’s happening.  Please correct me if I'm wrong.

Further, I'm having trouble with the data that arises from the parsing. The parsed midi file gives me e.g. {"bpm": 60, "ticks": 3840}.  If I try to use that ticks value to schedule time for the tempo change, it is in the wrong spot.  But it should be at the right spot.  A tick is a tick is a tick, and that tick should always be associated with that spot in the music, no matter the tempo.  I've done some checking to make sure that the ticks in the parsed object add up correctly, and they do.   But when the file is played in the Transport, with the tempo changes scheduled at those tick points, they don't happen at those spots in the music.  Something seems to get lost in the parsing.    

So now I’m stuck.  I haven’t been able to conceive a way to mitigate this double effect. If I use the parsed midi file, then the transport doesn’t know the correct position.  If I tell Transport the correct position, I get this double effect.

Maybe this is not an issue at all, and merely a misunderstanding on my part about how it is supposed to work.  
**Can you confirm if this is really an issue?  
If this is how it’s supposed to work?  
And, if so, can you suggest a strategy to work with this material to have the Transport know where it is?**

I’ve put together an online example to illustrate my points. 
http://www.gettysburg.edu/~rnatter/MIDI_exampleRN.html

It is based on your own DEMO at https://tonejs.github.io/Midi/

I’ve adapted your DEMO to put the data into Tone.Parts, so I can schedule in the Transport.
**The relevant code passages are in lines 154-180**

I’ve set it up to load a sample file easily; you’ll see the default at the top of the page.
If you need it, that file is at http://www.gettysburg.edu/~rnatter/testTempoOnly.mid

Here's an image of the music used to make the file.
![testTempoOnly](https://user-images.githubusercontent.com/26484331/62090317-6989da00-b23a-11e9-9248-d37b5d7c9aa4.png)

I hope I've been clear and complete.  Happy to provide more information if needed.
Thank you very much for your consideration.

**Comment by rnatter** [comment]
Please note that I edited this about an hour after I wrote it, to reflect a better understanding of ticks.

**Comment by tambien** [comment]
As you mentioned, there are two timing values, 'ticks' and 'time'. Time already has the tempo changes accounted for it while ticks are tempo-relative. So in order to get the right timing you'll need to schedule the tempo changes on the transport by doing something like: `Transport.bpm.setValueAtTime(bpm, time)`

The ticks timing is not a universal measurement. The timing is based on the PPQ (pulses per quarter) or, in other words, the number of ticks per quarter note. It's possible to parse a midi file that has 96 or 400 PPQ, while Tone.js has a default PPQ or 192. In which case, you'll either have to set Tone's PPQ or compute the correct PPQ based on the ratio between the two PPQ's.

**Comment by rnatter** [comment]
Thank you very much for your quick response.  I really appreciate it. 
I have tried the Transport.bpm.setValueAtTime(bpm, time) method, with results that I don't really understand.  Here is the same example as I posted before, but using that method; relevant lines at 162-166.  http://www.gettysburg.edu/~rnatter/midi-svat.html

The PPQ thread is very helpful. Do I need to parse at the PPQ of the file?  Or does midi.js translate the PPQ to Tone's default of 192?
Put another way, would it be a good strategy to set the Tone PPQ to the PPQ of the file, and then the references to ticks would then match with the events?

**Comment by rnatter** [comment]
I have tried the PPQ matching strategy as above, to be found at http://www.gettysburg.edu/~rnatter/midi-svat-ppq.html 
Still unexpected results with regard to note lengths, but with tempo changes occurring at some correct points.

You mentioned that 'time' takes into account the tempo changes in the file, while 'ticks' does not.  (This makes complete sense to me.)  Is it possible that when using this information to populate a Part, one needs to use 'ticks' instead of 'time'?    Just an idea...
```
function makeSong(midi){
            Tone.Transport.ppq=midi.header.ppq
            const numofVoices = midi.tracks.length 
            const synths = []
            const partsHolder =[]  
```

            //************** Tell transport about bpm changes  ********************

            for (let i=0; i < midi.header.tempos.length; i++) {
				Tone.Transport.bpm.setValueAtTime(midi.header.tempos[i].bpm, midi.header.tempos[i].ticks + "i")
            }             

            //************** Create Synths and Parts, one for each track  ********************

            for (let i = 0; i < numofVoices; i++) {
                synths[i] = new Tone.PolySynth().toMaster()
                partsHolder[i]=midi.tracks[i].notes 
                var part = new Tone.Part(function(time,value){
                    synths[i].triggerAttackRelease(value.name, value.duration, time, value.velocity)
                },partsHolder[i]).start()                  
            } 
            console.log(Tone.Transport.ppq)  
        }`

**Comment by rnatter** [comment]
I have done some more work to test how the MIDI parser and Tone interact with each other, especially for creating Parts, correct positioning of tempo changes, and correct reporting of position on the Transport.  Tambien's response was very useful, thank you.

The PPQ thread was very helpful.  
To get the Transport.position to line up with the midi passage, the PPQ of the Transport needs to match that of the midi file.
This makes perfect sense once you realize that.
(And it's tricky, because if you don't match the Transport with the file, it will still SOUND right, because Tone is smart!)
Something simple like the following does the trick:

`Tone.Transport.PPQ = midi.header.ppq`

(BTW it must be "Tone.Transport.PPQ" and not "Tone.Transport.ppq"  That threw me for a while.)

-------------

As I said in my original post, it's clear that one must schedule the tempo changes across the Transport Timeline.  No other way for the Transport to know when to change tempo.

You suggested `Transport.bpm.setValueAtTime(bpm, time)`, but I had difficulty getting that method to work and have it affect the actual .bpm value of the Transport.  I had more success with it today, using hardcoded values, e.g. Tone.Transport.bpm.setValueAtTime(80, .5), but using it with tick values instead, e.g. Transport.bpm.setValueAtTime(120, "30i") did not work.   I imagine that that method is not set up to accept tick notation, but haven't dug into the source to confirm.  It IS called "setValueAtTIME" after all.  Am I correct about this?

I abandoned that strategy because I suspect that "time" is the wrong way to schedule these events in this tempo-setting context.  "time" is dependent on tempo: a quarter note at 60bpm will take 1 sec, but at 120bpm will sound for .5 seconds.  When setting bpm across a passage of events, the time of the later events depends upon the time of the earlier events. If the Transport doesn't recalculate all of the earlier times each instance a bpm is set, how can it know what time to set a later event, if there have been tempo changes along the way?
   
So, in this many-tempo-setting context, I believe "time" to be undependable.
   
But ticks are dependable.  How long each tick lasts depends on BPM, but every quarter note will take the same number of ticks, and will occur at the same tick along the timeline, no matter the tempo. 
This means that the key to this issue is to always use ticks as the basis to tell the Transport where something should happen, at least when dealing with tempo changes.  Upshot is, I was able to use `Tone.Transport.schedule()` with ticks to achieve the goal:

```
            for (let i=0; i < midi.header.tempos.length; i++) {
                Tone.Transport.schedule(function(time){
                Tone.Transport.bpm.value = midi.header.tempos[i].bpm
                }, midi.header.tempos[i].ticks + "i");    
            }
```

-------------

The third issue was with putting the parsed midi data into a Tone.Part so that I could schedule a reusable object along the Transport. 
The constructor for a Tone.Part takes "time" (explicitly) as one of it's parameters.  

```
//use an array of objects as long as the object has a "time" attribute
var part = new Tone.Part(function(time, value){
	//the value is an object which contains both the note and the velocity
	synth.triggerAttackRelease(value.note, "8n", time, value.velocity);
}, [{"time" : 0, "note" : "C3", "velocity": 0.9}, {"time" : "0:2", "note" : "C4", "velocity": 0.5}
]).start(0);
```

If I'm correct above about ticks being more dependable than time (in the context of setting tempos), it makes sense to use ticks as the basis for the "time" value to be given to the Part.  It seems that to schedule LATER events properly along a Part using time as the scheduler, the Part would always have to know about all of the tempo changes of the EARLIER events along the Part, otherwise the spots are wrong.  But the Part needs a "time" parameter, so I "tricked" it to take ticks for this parameter.
The MIDI parser gets the ticks from the midi file, so I replaced all of the "time" values in the midi object with "tick" values.

```
            for (let i = 0; i < numofVoices; i++) {
            midi.tracks[i].notes.forEach(note => {
                note.time = note.ticks + "i"
                })
            } 
``` 

This feels a bit hacky, but it worked. Fortunately Tone is flexible enough to use time expressed in many ways.  Using these ticks values in the Parts constructor scheduled the events along the timeline at points that are consistent no matter what tempo is applied at what point.  

Using three things together worked:
• Setting PPQ of Transport to match the ppq of the file
• Scheduling the bpm changes along the Transport using ticks as the time basis
• Using the Part constructor using ticks as the time basis (hacky, but effective)

(Code below could be more efficient, but is illustrative this way)

       ```
         function makeSong(midi){
            Tone.Transport.PPQ = midi.header.ppq
            const numofVoices = midi.tracks.length 
            const synths = [] 

            //************** Tell Transport about Time Signature changes  ********************
            for (let i=0; i < midi.header.timeSignatures.length; i++) {
                Tone.Transport.schedule(function(time){
                    Tone.Transport.timeSignature = midi.header.timeSignatures[i].timeSignature;
                }, midi.header.timeSignatures[i].ticks + "i");    
            }

            //************** Tell Transport about bpm changes  ********************
            for (let i=0; i < midi.header.tempos.length; i++) {
                Tone.Transport.schedule(function(time){
                    Tone.Transport.bpm.value = midi.header.tempos[i].bpm + CW.tempoOffset;
                }, midi.header.tempos[i].ticks + "i");    
            }

            //************ Change time from seconds to ticks in each part  *************
            for (let i = 0; i < numofVoices; i++) {
                midi.tracks[i].notes.forEach(note => {
                    note.time = note.ticks + "i"
                })
            }
            
            //************** Create Synths and Parts, one for each track  ********************
            for (let i = 0; i < numofVoices; i++) {
                synths[i] = new Tone.PolySynth().toMaster()

                var part = new Tone.Part(function(time,value){
                    synths[i].triggerAttackRelease(value.name, value.duration, time, value.velocity)
                },midi.tracks[i].notes).start()                  
            }  
        }
       ```

------------
I'm not really sure if these constitute "issues" Tonejs/MIDI or not.
I had difficulties with them, so I thought it might be useful to share with the community.
Maybe it would have been better to put this in the Google Group forum (and I will do so for that community.)

My question to Tambien are:

Am I correct about my observations above?
Do I describe the context about setting tempos and their relationships to time and ticks correctly?
Is there anything wrong with the observations I've made above?  Would be helpful to know for strategies going forward.

Thanks very much for your amazing work on Tone!

**Comment by motifn** [comment]
Hi @rnatter,

Maybe I can help, as @tambien is a bit overloaded right now, and I might be able to answer your question, given I've successfully exported songs with tempo changes. Here's an example (click the "Export as MIDI" button):

https://www.motifn.com/help/tempo

This works by using the tone.js midi library as follows:

  * Add `TempoEvent`s to the midi header, with each event specifying the `bpm` you want, and the `ticks`, by multiplying the header's `ppq` by the logical beat the tempo change occurs
  * Remember to call `update` after setting the midi header
  * Set notes using the `time` property, as a number in *seconds*

The only tricky part, might be in calculating the `time` property. You need to be able to convert a logical beat time into an absolute time in seconds. You might be able to use header's `ticksToSeconds` method (can't confirm whether that will work or not as my implementation uses an independent timing system).

Hope that helps,
Ben

**Comment by rnatter** [comment]
Hi motifn
Thanks so much for your reply.  I will check out your solution in more depth, but at first glance it seems to use the same principle as mine, in which one schedules BPM changes based on ticks (which are always coordinated with their proper spot in the music, regardless of previous tempo changes) instead of time.  It seems to work pretty well.  Check out
http://public.gettysburg.edu/~rnatter/midi-ppqWorking.html

Let me know what you think of my solution!

**Comment by motifn** [comment]
Checked your solution with a couple of midi files w/ tempo changes - seems to work well.
