### ISSUE TITLE
negative duration for notes

### ISSUE THREAD

**Issue by tareqdayya** [Tonejs/MidiConvert#86]
Hi,

For some reason, i'm getting negative durations for some notes in this file:
[http://www.kunstderfuge.com/-/midi.asp?file=tchaikovsky_seasons_6_(c)oguri.mid](url)

**Comment by tambien** [comment]
looks like there were some cases where there were multiple noteOff's possible for a corresponding noteOn and it was choosing the wrong one. Now checking that the noteOff time must be greater than the noteOn time. Tested with the file that you posted and doesn't produce negative times anymore.
