### ISSUE TITLE
No timing for program changes, only allows for a single program on midi channel? 

### ISSUE THREAD

**Issue by ghost** [Tonejs/MidiConvert#90]
It seem like your midi import parser? script do not allow for more then one program per midichannel, because there is no timing info, like it is for the CC's?

I am not sure about the situation for the pitchbend but it could be the same, at least it seem so.
I do like your parser because it so easy to see what is going on, but it would be nice if program change on channel did work?

Maybe this can help you catch the events and their timings, because there must/could be in midifile?

if (d0 > "191" && d0<"208") {listProgramCh(i,d0,d1,d2,t0); }
if (d0 > "223" && d0<"241") {pitchBend(i,d0,d1,d2,t0); }
Yeah it is much simpler with metaevent then fiddling bits in a midifile.....
I really do not want to write a parser from scratch.

Or do i understand the structure wrong?

 "93": [
          {
            "number": 93,
            "ticks": 96,
            "time": 0.4701171875,
            "value": 0.5039370078740157
          }
        ]
      },
      "pitchBends": [],
      "instrument": {
        "family": "organ",
        "name": "rock organ",
        "number": 18
      },
      "name": "Lead Rock Organ",
      "notes": [
        {
          "duration": 0.2294921875,
          "durationTicks": 47,
          "midi": 76,
          "name": "E5",
          "ticks": 1920,
          "time": 9.3763671875,
          "velocity": 0.968503937007874
        },

**Comment by jambots** [comment]
I have this issue also.  I only see value of 0 and time of 0 in an object in the array for entries "0" and "32" of midi.tracks[0].controlChanges while the documentation shows an array of objects with keys: number, ticks, time, and value. My mid file does contain the program changes. Is there a misunderstanding of how to access the data or is tonejs in fact not representing program changes over time? Does 'Won't fix' mean it is a known problem? If so please update the documentation.
