### ISSUE TITLE
Setting BPM on a Midi object

### ISSUE THREAD

**Issue by felixturner** [Tonejs/MidiConvert#93]
When I load a midi file, the BPM is assumed to be 120. If the actual BPM is not 120, the generated time values are incorrect. Is there a way to set the BPM on the generated midi object? 

(Note: I don't have the entire Tone lib installed for this project, just '@tonejs/midi')

thanks for Tone.js!

**Comment by felixturner** [comment]
figured it out:
```
midi = await Midi.fromUrl(path);
midi.header.setTempo(124);
```

might be worth adding to the docs?

**Comment by braebo** [comment]
Been stuck for 2 days and this just saved me.  Thank you!!
