### ISSUE TITLE
Unable to get note channel from the JSON format

### ISSUE THREAD

**Issue by ScroogeD2** [Tonejs/MidiConvert#94]
I'm trying to ignore percussion in a program that I'm writing, but it seems to be impossible to get the channels of individual notes from the JSON generated by Tonejs? You can only get the channel of an entire track, and that can be a problem if you're trying to read format 0 MIDI files, as those contain all messages in a single track. With that, there's no way to determine if a note is percussion or something else.  

Love the project anyway though, thanks a lot for it.

**Comment by xenjacob** [comment]
@ScroogeD2, I believe I've created a good fix for this in my fork. https://github.com/xenjacob/Midi <<< Not sure if proper open source protocol here but have created a pull request for it also.

**Comment by ScroogeD2** [comment]
Looks great, but you might want to update your fork before making a pull request, since currently it's 35 commits behind Tonejs/Midi (just clone the Tonejs/Midi repo, readd your modifications, then commit and push them to your fork and remake the pull request). I can't comment on the additions themselves though, not familiar enough with typescript.

**Comment by xenjacob** [comment]
Thanks @ScroogeD2 . Was able to complete updates and just update #105 .

**Comment by ScroogeD2** [comment]
Still relevant.
